#Filtering data -- using Logical(&, |) Operators

In [8]:
import pandas as pd

In [9]:
b=pd.read_csv("sample_data.csv")
b

            name  marks  age  salary
0    Ayesha Khan     87   22   45000
1      Ali Ahmed     76   25   52000
2     Sara Malik     92   21   48000
3    Usman Tariq     68   28   60000
4      Hira Shah     81   24   55000
5    Hamza Iqbal     73   26   50000
6     Zainab Ali     95   23   65000
7  Bilal Hussain     64   30   70000
8    Mariam Noor     89   22   47000
9   Daniyal Raza     78   27   58000

In [12]:
#Filtering
b[b["marks"] > 75]

           name  marks  age  salary
0   Ayesha Khan     87   22   45000
1     Ali Ahmed     76   25   52000
2    Sara Malik     92   21   48000
4     Hira Shah     81   24   55000
6    Zainab Ali     95   23   65000
8   Mariam Noor     89   22   47000
9  Daniyal Raza     78   27   58000

In [13]:
b[(b["marks"]>75) & (b["age"]>20)]

           name  marks  age  salary
0   Ayesha Khan     87   22   45000
1     Ali Ahmed     76   25   52000
2    Sara Malik     92   21   48000
4     Hira Shah     81   24   55000
6    Zainab Ali     95   23   65000
8   Mariam Noor     89   22   47000
9  Daniyal Raza     78   27   58000

In [16]:
b[(b["marks"]> 90) | (b["salary"]>55000)]

            name  marks  age  salary
2     Sara Malik     92   21   48000
3    Usman Tariq     68   28   60000
6     Zainab Ali     95   23   65000
7  Bilal Hussain     64   30   70000
9   Daniyal Raza     78   27   58000

In [14]:
b[(b["marks"]>80) & (b["age"]>20) & (b["salary"]>50000)]

         name  marks  age  salary
4   Hira Shah     81   24   55000
6  Zainab Ali     95   23   65000

In [15]:
b[(b["marks"]>85) | (b["age"]>24) & (b["salary"]> 60000) ]

            name  marks  age  salary
0    Ayesha Khan     87   22   45000
2     Sara Malik     92   21   48000
6     Zainab Ali     95   23   65000
7  Bilal Hussain     64   30   70000
8    Mariam Noor     89   22   47000